### ISSUE TITLE
Solve crashes when dependency calculation takes more than 1 second with ruby solver

### ISSUE THREAD

**Issue by josacar** [berkshelf/solve#50]
Solve 2 crashes when resolution takes more than 1 second with ruby solver. [Molinillo](https://github.com/CocoaPods/Molinillo/blob/master/lib/molinillo/resolution.rb#L285-L299) calls ui to update UI every [1 second](https://github.com/berkshelf/solve/blob/master/lib/solve/ruby_solver.rb#L99-L101).

This is the stacktrace: 

```
/home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/molinillo-0.2.3/lib/molinillo/resolution.rb:293:in `indicate_progress': undefined method `indicate_progress' for #<Solve:
:RubySolver:0x007f28b91fa408> (NoMethodError)
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/molinillo-0.2.3/lib/molinillo/resolution.rb:63:in `resolve'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/molinillo-0.2.3/lib/molinillo/resolver.rb:40:in `resolve'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/solve-2.0.1/lib/solve/ruby_solver.rb:177:in `resolve_with_error_wrapping'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/solve-2.0.1/lib/solve/ruby_solver.rb:72:in `resolve'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/solve-2.0.1/lib/solve.rb:64:in `it!'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/resolver.rb:76:in `resolve'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/installer.rb:175:in `install_from_universe'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/installer.rb:39:in `run'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/berksfile.rb:374:in `install'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/berksfile.rb:399:in `update'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/cli.rb:163:in `update'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/cli.rb:52:in `dispatch'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/lib/berkshelf/cli.rb:27:in `execute!'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bundler/gems/berkshelf-c7bd4b19cc11/bin/berks:5:in `<top (required)>'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bin/berks:23:in `load'
        from /home/vagrant/code/platform/infra/vendor/bundle/ruby/2.2.0/bin/berks:23:in `<main>'
```

**Comment by reset** [comment]
@josacar thanks for the bug report, this should be an easy fix

**Comment by josacar** [comment]
Yes, adding the method solves the crash, I didn't submit a PR as it's new behavior and I didn't know what to implement. I can submit a PR if you tell me the implementation, maybe is as easy as:

```ruby
def indicate_progress
  print '.'
end
```

**Comment by reset** [comment]
@josacar I think the easiest fix is just to no-op the callback function. We aren't using it and didn't intend for it to be called in the first place

**Comment by josacar** [comment]
PR submitted with no-op
